apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: zoyber
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  tls:
  - hosts:
    - hashbang.arctair.com
    secretName: hashbang-tls
  rules:
  - host: hashbang.arctair.com
    http:
      paths:
      - path: /()(.*)
        backend:
          serviceName: hashbang
          servicePort: 8080
  - host: painkiller.arctair.com
    http:
      paths:
      - path: /(layouts)(.*)
        backend:
          serviceName: layouts
          servicePort: 8080
      - path: /ktor-starter(/|$)(.*)
        backend:
          serviceName: ktor-starter
          servicePort: 8080
      - path: /ktor-starter-dark(/|$)(.*)
        backend:
          serviceName: ktor-starter-dark
          servicePort: 8080
      - path: /stepper(/|$)(.*)
        backend:
          serviceName: stepper
          servicePort: 8080
      - path: /stepper-dark(/|$)(.*)
        backend:
          serviceName: stepper-dark
          servicePort: 8080
      - path: /stepper-target(/|$)(.*)
        backend:
          serviceName: stepper-target
          servicePort: 8080
      - path: /stepper-target-dark(/|$)(.*)
        backend:
          serviceName: stepper-target-dark
          servicePort: 8080
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@arctair.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: info@arctair.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
